include:
  - project: 'tech/gitlab-ci-template'
    ref: master
    file: '.k8s-runner.yml'

variables:
  PROJECT: tech
  APP_NAME: volio-backend-web-cms
  APPLICATIONS: volio-backend-web-cms,volio-backend-slide-show,volio-backend-jacat-cms,volio-backend-test-cms
